import type { KanboomConfig } from '../types/kanban';
export declare function useKanban<TCard = any, TColumn = any>(config?: KanboomConfig<TCard, TColumn>): {
    activeId: string | null;
    overId: string | null;
    overSide: "top" | "bottom" | "left" | "right" | null;
    viewingCardId: string | null;
    editingCardId: string | null;
    addingCardInColumnId: string | null;
    editingColumnId: string | null;
    setViewingCardId: (id: string | null) => void;
    clearViewingCardId: () => void;
    handleDragStart: (cardId: string) => void;
    handleDragOver: (id: string | null, side?: "top" | "bottom" | "left" | "right" | null) => void;
    handleDragEnd: () => void;
    moveCard: (cardId: string, sourceColumnId: string, targetColumnId: string, index: number) => void;
    addCard: (columnId: string, card: Omit<import("..").KanboomCard, "id">) => string;
    updateCard: (cardId: string, updates: Partial<import("..").KanboomCard>) => void;
    deleteCard: (cardId: string) => void;
    duplicateCard: (cardId: string) => string;
    setEditingCardId: (id: string | null) => void;
    clearEditingCardId: () => void;
    setAddingCardInColumnId: (id: string | null) => void;
    clearAddingCardInColumnId: () => void;
    addColumn: (column: Omit<import("..").KanboomColumn, "id" | "cardIds">, position?: number) => string;
    addColumnWithCard: (cardId: string, sourceColId: string, columnData: Omit<import("..").KanboomColumn, "id" | "cardIds">) => void;
    updateColumn: (columnId: string, updates: Partial<import("..").KanboomColumn>) => void;
    deleteColumn: (columnId: string, moveCardsTo?: string) => void;
    moveColumn: (columnId: string, newIndex: number) => void;
    setEditingColumnId: (id: string | null) => void;
    clearEditingColumnId: () => void;
    clearBoard: () => void;
    config: {
        dragActivationDistance: number;
        touchActivationDelay: number;
        virtualOverscan: number;
        estimatedCardHeight: number;
        columnWidth: number;
        columnMinHeight: number;
        gap: number;
        allowAdd: boolean;
        allowEdit: boolean;
        allowColumnAdd: boolean;
        allowColumnEdit: boolean;
        allowColumnDelete: boolean;
        allowColumnReorder: boolean;
        allowFilters: boolean;
        showURLSync: boolean;
    };
    filters: import("..").KanbanFilters;
    setSearchQuery: (query: string) => void;
    addFilterGroup: (group: import("..").FilterGroup) => void;
    updateFilterGroup: (groupId: string, updates: Partial<import("..").FilterGroup>) => void;
    removeFilterGroup: (groupId: string) => void;
    removeFilterRule: (groupId: string, ruleId: string) => void;
    setFilters: (filters: import("..").KanbanFilters) => void;
    clearFilters: () => void;
    setBoardData: (data: import("..").KanboomData) => void;
    setConfig: (config: Partial<KanboomConfig>) => void;
    setActiveId: (id: string | null) => void;
    cards: Record<string, import("..").KanboomCard>;
    columns: Record<string, import("..").KanboomColumn>;
    columnOrder: string[];
};
//# sourceMappingURL=use-kanban.d.ts.map